export const categories = [
    { id: 1, description: "Multi-player" },
    { id: 2, description: "Single-player" },
    { id: 6, description: "Mods (require HL2)" },
    { id: 7, description: "Mods (require HL1)" },
    { id: 8, description: "Valve Anti-Cheat enabled" },
    { id: 9, description: "Co-op" },
    { id: 10, description: "Demos" },
    { id: 12, description: "HDR available" },
    { id: 13, description: "Captions available" },
    { id: 14, description: "Commentary available" },
    { id: 15, description: "Stats" },
    { id: 16, description: "Includes Source SDK" },
    { id: 17, description: "Includes level editor" },
    { id: 18, description: "Partial Controller Support" },
    { id: 19, description: "Mods" },
    { id: 20, description: "MMO" },
    { id: 21, description: "Downloadable Content" },
    { id: 22, description: "Steam Achievements" },
    { id: 23, description: "Steam Cloud" },
    { id: 24, description: "Shared/Split Screen" },
    { id: 25, description: "Steam Leaderboards" },
    { id: 27, description: "Cross-Platform Multiplayer" },
    { id: 28, description: "Full controller support" },
    { id: 29, description: "Steam Trading Cards" },
    { id: 30, description: "Steam Workshop" },
    { id: 31, description: "VR Support" },
    { id: 32, description: "Steam Turn Notifications" },
    { id: 33, description: "Native Steam Controller" },
    { id: 35, description: "In-App Purchases" },
    { id: 36, description: "Online PvP" },
    { id: 37, description: "Shared/Split Screen PvP" },
    { id: 38, description: "Online Co-op" },
    { id: 39, description: "Shared/Split Screen Co-op" },
    { id: 40, description: "SteamVR Collectibles" },
    { id: 41, description: "Remote Play on Phone" },
    { id: 42, description: "Remote Play on Tablet" },
    { id: 43, description: "Remote Play on TV" },
    { id: 44, description: "Remote Play Together" },
    { id: 45, description: "Cloud Gaming" },
    { id: 46, description: "Cloud Gaming (NVIDIA)" },
    { id: 47, description: "LAN PvP" },
    { id: 48, description: "LAN Co-op" },
    { id: 49, description: "PvP" },
    { id: 50, description: "Additional High-Quality Audio" },
    { id: 51, description: "Steam Workshop" },
    { id: 52, description: "Tracked Controller Support" },
    { id: 53, description: "VR Supported" },
    { id: 54, description: "VR Only" }
  ];