export const categories = [
  { id: 1, description: "Multi-player", translation: "Для нескольких игроков" },
  { id: 2, description: "Single-player", translation: "Для одного игрока" },
  { id: 6, description: "Mods (require HL2)", translation: "Модификации (требуют HL2)" },
  { id: 7, description: "Mods (require HL1)", translation: "Модификации (требуют HL1)" },
  { id: 8, description: "Valve Anti-Cheat enabled", translation: "Античит Valve" },
  { id: 9, description: "Co-op", translation: "Кооператив (локально)" },
  { id: 10, description: "Demos", translation: "Демо" },
  { id: 12, description: "HDR available", translation: "HDR доступен" },
  { id: 13, description: "Captions available", translation: "Доступны субтитры" },
  { id: 14, description: "Commentary available", translation: "Доступны комментарии" },
  { id: 15, description: "Stats", translation: "Статистика" },
  { id: 16, description: "Includes Source SDK", translation: "Source SDK" },
  { id: 17, description: "Includes level editor", translation: "Редактор уровней" },
  { id: 18, description: "Partial Controller Support", translation: "Поддержка контроллера (частично)" },
  { id: 19, description: "Mods", translation: "Моды" },
  { id: 20, description: "MMO", translation: "ММО" },
  { id: 21, description: "Downloadable Content", translation: "DLC" },
  { id: 22, description: "Steam Achievements", translation: "Достижения Steam" },
  { id: 23, description: "Steam Cloud", translation: "Облачное хранилище Steam" },
  { id: 24, description: "Shared/Split Screen", translation: "Общий/Разделенный экран" },
  { id: 25, description: "Steam Leaderboards", translation: "Таблицы лидеров Steam" },
  { id: 27, description: "Cross-Platform Multiplayer", translation: "Кроссплатформенный мультиплеер" },
  { id: 28, description: "Full controller support", translation: "Поддержка контроллера (полностью)" },
  { id: 29, description: "Steam Trading Cards", translation: "Коллекционные карточки Steam" },
  { id: 30, description: "Steam Workshop", translation: "Мастерская Steam" },
  { id: 31, description: "VR Support", translation: "Поддержка VR" },
  { id: 32, description: "Steam Turn Notifications", translation: "Уведомления Steam Turn" },
  { id: 33, description: "Native Steam Controller", translation: "Поддержка контроллера Steam" },
  { id: 35, description: "In-App Purchases", translation: "Покупки в приложении" },
  { id: 36, description: "Online PvP", translation: "Онлайн PvP" },
  { id: 37, description: "Shared/Split Screen PvP", translation: "Общий/Разделенный экран PvP" },
  { id: 38, description: "Online Co-op", translation: "Кооператив (онлайн)" },
  { id: 39, description: "Shared/Split Screen Co-op", translation: "Общий/Разделенный экран Кооператив" },
  { id: 40, description: "SteamVR Collectibles", translation: "Коллекционные предметы для SteamVR" },
  { id: 41, description: "Remote Play on Phone", translation: "Remote Play (телефон)" },
  { id: 42, description: "Remote Play on Tablet", translation: "Remote Play (планшет)" },
  { id: 43, description: "Remote Play on TV", translation: "Remote Play (телевизор)" },
  { id: 44, description: "Remote Play Together", translation: "Remote Play Together" },
  { id: 45, description: "Cloud Gaming", translation: "Облачное гейминг" },
  { id: 46, description: "Cloud Gaming (NVIDIA)", translation: "Облачное гейминг (NVIDIA)" },
  { id: 47, description: "LAN PvP", translation: "LAN PvP" },
  { id: 48, description: "LAN Co-op", translation: "LAN Кооператив" },
  { id: 49, description: "PvP", translation: "PvP" },
  { id: 50, description: "Additional High-Quality Audio", translation: "Высококачественный звук" },
  { id: 51, description: "Steam Workshop", translation: "Мастерская Steam" },
  { id: 52, description: "Tracked Controller Support", translation: "Поддержка отслеживаемого контроллера" },
  { id: 53, description: "VR Supported", translation: "Поддержка VR" },
  { id: 54, description: "VR Only", translation: "Только для VR" }
];


export const genres = [
  { id: 1, description: "Action", translation: "Экшен" },
  { id: 2, description: "Strategy", translation: "Стратегия" },
  { id: 3, description: "RPG", translation: "Ролевая игра" },
  { id: 4, description: "Casual", translation: "Казуальная" },
  { id: 9, description: "Racing", translation: "Гонки" },
  { id: 18, description: "Sports", translation: "Спорт" },
  { id: 23, description: "Indie", translation: "Инди" },
  { id: 25, description: "Adventure", translation: "Приключения" },
  { id: 28, description: "Simulation", translation: "Симулятор" },
  { id: 29, description: "Massively Multiplayer", translation: "Массово многопользовательская" },
  { id: 37, description: "Free to Play", translation: "Бесплатная" },
  { id: 50, description: "Accounting", translation: "Бухгалтерия" },
  { id: 51, description: "Animation & Modeling", translation: "Анимация и моделирование" },
  { id: 52, description: "Audio Production", translation: "Звуковое производство" },
  { id: 53, description: "Design & Illustration", translation: "Дизайн и иллюстрация" },
  { id: 54, description: "Education", translation: "Образование" },
  { id: 55, description: "Photo Editing", translation: "Редактирование фотографий" },
  { id: 56, description: "Software Training", translation: "Обучение программам" },
  { id: 57, description: "Utilities", translation: "Утилиты" },
  { id: 58, description: "Video Production", translation: "Видео производство" },
  { id: 59, description: "Web Publishing", translation: "Публикация в сети" },
  { id: 60, description: "Game Development", translation: "Разработка игр" },
  { id: 70, description: "Early Access", translation: "Ранний доступ" },
  { id: 71, description: "Sexual Content", translation: "Сексуальный контент" },
  { id: 72, description: "Nudity", translation: "Обнаженность" },
  { id: 73, description: "Violent", translation: "Жестокость" },
  { id: 74, description: "Gore", translation: "Кровавость" },
  { id: 80, description: "Movie", translation: "Фильм" },
  { id: 81, description: "Documentary", translation: "Документальный" },
  { id: 82, description: "Episodic", translation: "Эпизодический" },
  { id: 83, description: "Short", translation: "Короткометражный" },
  { id: 84, description: "Tutorial", translation: "Обучающий" },
  { id: 85, description: "360 Video", translation: "360 Видео" }
];

  